# BASE_URL=http://localhost:9093;DATASOURCE_PW=password2;DATASOURCE_URL=r2dbc:postgresql://localhost:5436/reactiveDB;DATASOURCE_USER=jamil;FLYWAY_URL=jdbc:postgresql://localhost:5436/reactiveDB
server:
  port: 9096
product:
  service:
    base:
      url: ${BASE_URL}
app:
  security:
    clientId: ${CLIENT_ID}


spring:
  application:
    name: reactive_project_01

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI}
          issuer-uri: ${JWT_ISSUER_URI}
          audiences: ${JWT_AUDIENCE}

  r2dbc:
    password: ${DATASOURCE_PW}
    username: ${DATASOURCE_USER}
    url: ${DATASOURCE_URL}
  flyway:
    default-schema: public
    schemas: public
    url: ${FLYWAY_URL}
    user: ${DATASOURCE_USER}
    password: ${DATASOURCE_PW}
    locations: classpath:${FLYWAY_LOCATION:/db/migration,/db/data} # ,/db/data

